#!/bin/bash
cd /rhome/lyu062/bigdata/TNC_Project/fq

for read1 in *R1.fastq
do
 ~/.local/bin/cutadapt -a GATCTCTTGGNTCTNGCATCGATGAAGAACG -q 20 -e 0.2 ./$read1 -o ../fq_trimmed/$read1
done

for read2 in *R2.fastq
do
~/.local/bin/cutadapt -a GGAAACCTTGTTACGACTTTTACTTCCTCTAAATGACCAA -q 20 -e 0.3 ./$read2 -o ../fq_trimmed/$read2
done

