#!/bin/bash  

#The PIPITS is divided into three consequential parts:

#1. Sequence preparation to join, convert, quality filter etc.
#2. Fungal ITS extraction to remove conserved regions
#3. Process the reads to produce an OTU abundance table and the taxonomic assignment table for downstream analysis
#Test it with a very small test dataset to ensure everything is set up correcly.


source activate pipits_env
cd /rhome/lyu062/bigdata/TNC_Project

# B1. Sequence Preparation
echo B1. Sequence Preparation

pispino_createreadpairslist -i fq_trimmed -o PIPITS_project/readpairslist.txt
pispino_seqprep -i fq_trimmed -o PIPITS_project/out_seqprep -l PIPITS_project/readpairslist.txt

# B2. Fungal ITS extraction
echo B2. Fungal ITS extraction
pipits_funits -i PIPITS_project/out_seqprep/prepped.fasta -o PIPITS_project/out_funits -x ITS1


# B3. Process sequences
echo B3. Process sequences

pipits_process -i PIPITS_project/out_funits/ITS.fasta -o PIPITS_project/out_process

# Once all finished, we can leave Conda environment
source deactivate

pipits_funguild.py -i PIPITS_project/out_process/otu_table.txt -o PIPITS_project/out_process/otu_table_funguild.txt
