#!/bin/bash                                                                                                          
cd /rhome/lyu062/bigdata/TNC_Project/FastQC                                                                          
./fastqc --outdir=/rhome/lyu062/bigdata/TNC_Project/fq_report /rhome/lyu062/bigdata/TNC_Project/fq/*.fastq  
